import Image from "next/image";

export default function Page() {
  return (
    <main style={{ padding: 24, minHeight: "100vh", display: "grid", placeItems: "center" }}>
      <section
        style={{
          width: "100%",
          maxWidth: 520,
          borderRadius: 24,
          background: "rgba(255, 255, 255, 0.6)",
          backdropFilter: "blur(12px)",
          WebkitBackdropFilter: "blur(12px)",
          boxShadow: "0 10px 30px rgba(0,0,0,0.2)",
          padding: 24,
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 14 }}>
          <Image src="/brand/logo.png" alt="Brand logo" width={28} height={28} priority />
          <h1 style={{ margin: 0, fontSize: 24 }}>coso-template</h1>
        </div>

        <p style={{ marginTop: 0, marginBottom: 16, opacity: 0.85 }}>Generated by coso-factory.</p>

        <form style={{ display: "grid", gap: 12 }}>
          <label style={{ display: "grid", gap: 6 }}>
            <span>Name</span>
            <input
              name="name"
              placeholder="Your name"
              style={{ borderRadius: 12, border: "1px solid rgba(15, 23, 42, 0.2)", padding: "10px 12px" }}
            />
          </label>
          <label style={{ display: "grid", gap: 6 }}>
            <span>Birth date</span>
            <input
              name="birthDate"
              type="date"
              style={{ borderRadius: 12, border: "1px solid rgba(15, 23, 42, 0.2)", padding: "10px 12px" }}
            />
          </label>
        </form>
      </section>
    </main>
  );
}
