import Image from "next/image";

export default function Page() {
  return (
    <main className="grid min-h-screen place-items-center p-6">
      <section className="w-full max-w-[520px] rounded-2xl bg-white/60 p-6 shadow-lg backdrop-blur-md">
        <div className="mb-3 flex items-center gap-2.5">
          <Image src="/brand/logo.png" alt="Brand logo" width={28} height={28} priority />
          <h1 className="m-0 text-2xl">coso-template</h1>
        </div>

        <p className="mb-4 mt-0 opacity-85">Generated by coso-factory.</p>

        <form className="grid gap-3">
          <label className="grid gap-1.5">
            <span>Name</span>
            <input
              name="name"
              placeholder="Your name"
              className="rounded-xl border border-slate-900/20 px-3 py-2.5"
            />
          </label>
          <label className="grid gap-1.5">
            <span>Birth date</span>
            <input name="birthDate" type="date" className="rounded-xl border border-slate-900/20 px-3 py-2.5" />
          </label>
        </form>
      </section>
    </main>
  );
}
